# 1. Create a 3x3x3 array with random values 

In [2]:
import numpy as np

In [10]:
ran = np.random.random([3,3,3])
ran

array([[[0.90348725, 0.01013082, 0.08484723],
        [0.31072155, 0.50854562, 0.59910784],
        [0.6182289 , 0.31277156, 0.7007302 ]],

       [[0.60794387, 0.83799955, 0.75194631],
        [0.38831019, 0.47175637, 0.52912298],
        [0.80173742, 0.06888663, 0.54138909]],

       [[0.40962869, 0.08019081, 0.18396088],
        [0.03623542, 0.1042663 , 0.63390427],
        [0.5549207 , 0.60516135, 0.01487282]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [11]:
x = np.diag([1,2,3,4,5])
x

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [64]:
# function to print Checkerboard pattern 
def printcheckboard(n): 
      
    print("Checkerboard pattern:") 
  
    # create a n * n matrix 
    x = np.zeros((n, n), dtype = int) 
  
    # fill with 1 the alternate rows and columns 
    x[1::2, ::2] = 1
    x[::2, 1::2] = 1
      
    # print the pattern 
    for i in range(n): 
        for j in range(n): 
            print(x[i][j], end =" ")  
        print()  

# 8X8 Checkerboard    
n = 8
printcheckboard(n)

Checkerboard pattern:
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 


# 4. Normalize a 5x5 random matrix

In [17]:
Z = np.random.random((5,5))
print("Original matrix: \n", Z)
Zmax,Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)

Original matrix: 
 [[0.15056906 0.66311308 0.07500453 0.5319588  0.27450237]
 [0.43340844 0.8449982  0.8950412  0.70677257 0.11159101]
 [0.65253028 0.20313665 0.8678062  0.32770492 0.4084093 ]
 [0.04560096 0.51861889 0.88110651 0.26324411 0.07939307]
 [0.13766947 0.11832585 0.39529164 0.11582065 0.59247142]]


In [18]:
print("Normalized matrix: \n", Z)

Normalized matrix: 
 [[0.12357326 0.72696358 0.03461523 0.57256275 0.26947324]
 [0.45654475 0.94108708 1.         0.77836153 0.07768651]
 [0.71450503 0.18545824 0.96793771 0.33210571 0.42711461]
 [0.         0.55685839 0.98359544 0.2562195  0.03978162]
 [0.10838727 0.08561508 0.4116719  0.08266584 0.64380098]]


# 5.  How to find common values between two arrays?

In [19]:
a = np.array([211,22,55,77,45,65,68])
print("Array a: ",a)
      
      
b = np.array([12,55,44,77,89,36,25,15])
print("Array b: ",b)
      
      
print("Common values between two arrays are:")
print(np.intersect1d(a, b))

Array a:  [11 22 55 77 45 65 68]
Array b:  [12 55 44 77 89 36 25 15]
Common values between two arrays are:
[55 77]


# 6.How to get the dates of yesterday, today and tomorrow?

In [21]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: \n",yesterday)

today = np.datetime64('today', 'D')
print("Today: \n",today)

tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: \n",tomorrow)

Yestraday: 
 2020-07-24
Today: 
 2020-07-25
Tomorrow: 
 2020-07-26


# 7. Consider two random array A and B, check if they are equal

In [23]:
a = np.random.randint(0,5,10)
print("First array:")
print(a)

b = np.random.randint(0,5,10)
print("Second array:")
print(b)

print("Test above two arrays are equal or not!")
equal = np.allclose(a, b)
print(equal)

First array:
[4 1 0 1 1 1 3 2 1 1]
Second array:
[2 2 1 4 3 4 2 1 0 1]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [24]:
a = np.random.random(10)
print("Array: ")
print(a)

a[a.argmax()] = 0
print("Maximum value replaced by 0:")
print(a)

Array: 
[0.69736083 0.20496561 0.90379981 0.61620248 0.8147367  0.35248903
 0.46247372 0.6411389  0.49970052 0.97395163]
Maximum value replaced by 0:
[0.69736083 0.20496561 0.90379981 0.61620248 0.8147367  0.35248903
 0.46247372 0.6411389  0.49970052 0.        ]


# 9. How to print all the values of an array?

In [29]:

a = np.arange(100)

print(*a)

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99


# 10.Subtract the mean of each row of a matrix

In [30]:
print("Matrix: ")
a = np.random.randint(0,100,10).reshape([2,5])
print(a)
print("\nSubtract the mean of each row of the said matrix:\n")
b = a - a.mean(axis=1, keepdims=True)
print(b)

Matrix: 
[[98 84 84 59 13]
 [56 51 31 92 44]]

Subtract the mean of each row of the said matrix:

[[ 30.4  16.4  16.4  -8.6 -54.6]
 [  1.2  -3.8 -23.8  37.2 -10.8]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [31]:
a = np.ones(5)
print("Original vector", a)

b = np.random.randint(0,len(a),10)
print("Index vector", b)

a += np.bincount(b, minlength=len(a))
print("Updated vector", a)

Original vector [1. 1. 1. 1. 1.]
Index vector [3 4 3 2 0 3 2 1 1 4]
Updated vector [2. 3. 3. 4. 3.]


# 12.How to get the diagonal of a dot product?

In [32]:
a = np.arange(9).reshape(3, 3)
print(a,"\n")

b = np.arange(9).reshape(3, 3)
print(b,"\n")

c = np.diag(a.dot(b))
print(c) 

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[ 15  54 111]


# 13.How to find the most frequent value in an array?

In [58]:
import scipy.stats as st
np.random.seed(42)
a = np.random.randint(0, 10, 20)
print("Array:")
print(a)

print("Most frequent value in the above array:")
m,p = st.mode(a, axis=0)
print( *m)


Array:
[6 3 7 4 6 9 2 6 7 4 3 7 7 2 5 4 1 7 5 1]
Most frequent value in the above array:
7


# 14.How to get the n largest values of an array

In [59]:
a = np.array([2,5,88,99,101,54,65,74,35,28,45])
print("Array:")
print(a)
n = 1
print("Maximum value is:")
print (a[np.argsort(a)[-n:]])

Array:
[  2   5  88  99 101  54  65  74  35  28  45]
Maximum value is:
[101]


# 15.How to create a record array from a regular array?

In [61]:
a = np.array(['Machine','Learning','Engineer'])
b = np.array([99,55,11])
c = np.array(['p','q','r'])
records= np.core.records.fromarrays([a, b, c])
print(records[0])
print(records[1])
print(records[2])

('Machine', 99, 'p')
('Learning', 55, 'q')
('Engineer', 11, 'r')
